# -*- coding: utf-8 -*-
"""29jan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CgrqbmcJiS9BWi6ELrcQS49WuZKublM6

1 Guido van Rossum
   2 Objct Oriented Programming and structured
   3 yes
   4 .py
   5 interpreted
   6 functions,modules and classes
   7 '#' is the character used for single line comment
   8 python --version (if this isn't the answer can you tell what it is in comments?)
   9 lambda
   ----------------
  10 Preferred Installer Program
  11 print(): Used to print values to the console.
     len(): Returns the length (number of items) of an object like a string, list, tuple, etc.
     type(): Returns the type of an object.
     input(): Reads a line of text from the user through the console.
     int(): Converts a value to an integer.
     float(): Converts a value to a floating-point number.
     str(): Converts a value to a string.
  12 79 characters
  13 simple too use and understand
     free and open source
     increased productivity
     interpreted language
     entensive library
  14 Memory management in Python involves a private heap containing all Python objects and data structures.
     The management of this private heap is ensured internally by the Python memory manager.
  15 To install Python on Windows and set the PATH variable, follow these steps:

1. **Download Python:**
   Go to the official Python website (https://www.python.org/downloads/windows/) and download the latest version of Python for Windows. Choose either the 32-bit or 64-bit version, depending on your system.

2. **Run the Installer:**
   Run the downloaded installer executable. Make sure to check the box that says "Add Python X.X to PATH" during the installation process. This will automatically set up the PATH variable for you.

3. **Custom Installation (Optional):**
   If you didn't select the "Add Python X.X to PATH" option during installation, you can still set up the PATH manually. Follow these steps:

   a. Complete the installation of Python.
   b. Find the installation directory. The default location is usually `C:\Program Files\PythonXX` (where XX is the version number).
   c. Copy the path to the Python installation directory.

4. **Set PATH Variable Manually (Optional):**
   If you need to set the PATH variable manually or adjust it after installation, follow these steps:

   a. Right-click on the "This PC" or "Computer" icon on your desktop or in File Explorer and select "Properties."
   b. Click on "Advanced system settings" on the left side.
   c. In the System Properties window, click on the "Environment Variables" button.
   d. Under "System variables," locate the "Path" variable and click on "Edit."
   e. Click "New" and paste the path to the Python installation directory (e.g., `C:\Program Files\PythonXX`) into the field.
   f. Click "OK" to close the windows and save the changes.

5. **Verify Python Installation:**
   Open Command Prompt (search for "cmd" in the Start menu) and type `python --version` or `python` and press Enter. If Python is installed and configured correctly, you should see the version number or the Python interactive shell.

Remember that if you set the PATH variable manually, you need to ensure that it's set correctly, including the correct version of Python you want to use. It's generally recommended to let the installer handle the PATH configuration during installation.
  16 yes
"""