# -*- coding: utf-8 -*-
"""30jan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aEwPYlRnFMWE06WHNkobNjWzKSa0ntms
"""

'''
1. In object-oriented programming(OOP),a class and an object are fundamental concepts that help structure and model real-world entities,behaviors,and interactions in your code.
Class:
 A class is a blueprint or template for creating objects.
 It defines the properties (attributes) and behaviors (methods) that the objects of that class will have.
 In other words, a class is a way to encapsulate data and functionality into a single unit.
 It serves as a prototype from which objects are created.
Object:
 An object is an instance of a class.
 It's a concrete representation of the data and behaviors defined by the class.
 Objects allow you to work with the characteristics and perform the actions described in the class.
 Each object created from a class is independent and can have its own unique values for the attributes defined in the class.

 2. the 4 pillars of oops are- abstraction, encapsulation, inheritance, and polymorphism

 3.The Default __init__ Constructor in python.
   Constructors are used to initializing the object’s state.
   The task of constructors is to initialize(assign values) to the data members of the class when an object of the class is created.
   Like methods, a constructor also contains a collection of statements(i.e. instructions) that are executed at the time of Object creation.
   It is run as soon as an object of a class is instantiated.
   The method is useful to do any initialization you want to do with your object.

4. It represents the instance or objects of a class and binds the attributes of a class with specific arguments.
   The use of self variable in Python helps to differentiate between the instance attributes (and methods) and local variables.

5. Inheritance allows us to define a class that inherits all the methods and properties from another class.
   Parent class is the class being inherited from, also called base class.
   Child class is the class that inherits from another class, also called derived class.
   '''



